Dragen_folder="/dragennfs/area1/trangth18/GDB/"
DV_folder="/dragennfs/area1/trangth18/GLNEXUS/"
#GATK_folder="/dragennfs/area1/trangth18/GATKDB/"
#GATK_folder="/dragennfs/area1/trangth18/GATK_combineGVCF/"
GATK_folder="/dragennfs/area7/testIllumina/dragen3.7/"
VQSR_folder="/dragennfs/area7/PopTest/GATK_VQSR/"

#GATK: raw pop file generated by dragen genotyper testPop_1016.gatk.joint_genotype.vcf.gz --> vqsr + normalize --> testPop_1016.gatk.norm.vqsr.vcf.gz
#Dragen: raw pop file testPop_1030.jointGenotype.hard-filtered.vcf.gz --> hard-filtered & normalize --> testPop_1014.norm.filltags.pass.vcf.gz
#DV: raw pop file testPop_1014.dv.vcf.gz --> hard-filtered & normalize --> testPop_1014.dv.norm.filtered.vcf.gz 

Consensus_dir="/dragennfs/area7/PopTest/Consensus/"
Ref_folder="/home/shared/references/Homo_sapiens_assembly38.fasta"

Current_folder=$(pwd)
GATK_root="/home/shared/tools/gatk-4.1.8.1/"

#---------------**** GATK ****---------------
GATK_folder="/dragennfs/area7/testIllumina/dragen3.7/"
VQSR_folder="/dragennfs/area7/PopTest/GATK_VQSR/"
sample="testPop_1016.gatk"
pbrun vqsr --in-vcf "$GATK_folder""$sample".joint_genotype.vcf.gz \
        --out-vcf  "$VQSR_folder""$sample".recalibrated_INDEL.vcf.gz \
        --out-recal "$VQSR_folder""$sample".recalibrate_INDEL_rawSNP.recal \
        --out-tranches "$VQSR_folder""$sample".recalibrate_INDEL.tranches \
        --resource mills,known=false,training=true,truth=true,prior=12.0:"${Resource_root}"Mills_and_1000G_gold_standard.indels.hg38.vcf.gz \
        --resource dbsnp,known=true,training=false,truth=false,prior=2.0:"${Resource_root}"Homo_sapiens_assembly38.dbsnp138.vcf.gz \
        --max-gaussians 4 --truth-sensitivity-level 99.0 \
        --annotation QD --annotation SOR --annotation DP --annotation FS --annotation MQRankSum --annotation ReadPosRankSum --mode INDEL

pbrun vqsr --in-vcf "$VQSR_folder""$sample".recalibrated_INDEL.vcf.gz \
        --out-vcf "${VQSR_folder}""$sample".recalibrated_variants.vcf.gz \
        --out-recal "$VQSR_folder""$sample".recalibrate_SNP.recal \
        --out-tranches "$VQSR_folder""$sample".recalibrate_SNP.tranches \
        --resource hapmap,known=false,training=true,truth=true,prior=15.0:"${Resource_root}"hapmap_3.3.hg38.vcf.gz \
        --resource omni,known=false,training=true,truth=true,prior=12.0:"${Resource_root}"1000G_omni2.5.hg38.vcf.gz \
        --resource 1000G,known=false,training=true,truth=false,prior=10.0:"${Resource_root}"1000G_phase1.snps.high_confidence.hg38.vcf.gz \
        --resource dbsnp,known=true,training=false,truth=false,prior=2.0:"${Resource_root}"Homo_sapiens_assembly38.dbsnp138.vcf.gz \
        --max-gaussians 6 --truth-sensitivity-level 99.0 \
        --annotation QD --annotation SOR --annotation DP --annotation FS --annotation MQRankSum --annotation ReadPosRankSum --mode SNP

bcftools view -f .,PASS "${VQSR_folder}""$sample".recalibrated_variants.vcf.gz -Oz -o "${VQSR_folder}""$sample".vqsr.vcf.gz
tabix -p vcf "${VQSR_folder}""$sample".vqsr.vcf.gz

vt decompose -s "${VQSR_folder}""$sample".vqsr.vcf.gz |vt normalize - -r "${Ref_folder}" | vt uniq - -o "${VQSR_folder}""$sample".norm.vqsr.vcf.gz
tabix -p vcf "${VQSR_folder}""$sample".norm.vqsr.vcf.gz

bcftools stats "$GATK_folder""$sample".joint_genotype.vcf.gz>"$GATK_folder""$sample".joint_genotype.bcftools_stats.txt
bcftools stats "${VQSR_folder}""$sample".vqsr.vcf.gz>"${VQSR_folder}""$sample".vqsr.bcftools_stats.txt
bcftools stats "${VQSR_folder}""$sample".norm.vqsr.vcf.gz>"${VQSR_folder}""$sample".norm.vqsr.bcftools_stats.txt

#---------------**** DV ****---------------
ls "$DV_root"*.bcf>"$DV_root"list.csv
params=$(cat "${DV_root}"list.csv | while read bam; do printf " $bam "; done);
cmd="bcftools concat "$params" -Oz -o "$DV_root"testPop_1014.dv.vcf.gz"

$cmd

tabix -p vcf "$DV_root"testPop_1014.dv.vcf.gz



bcftools stats "$DV_root"testPop_1014.dv.vcf.gz>"$DV_root"testPop_1014.dv.bcftools_stats.txt

tabix -p vcf "$DV_root"testPop_1014.dv.filtered.vcf.gz
bcftools stats "$DV_root"testPop_1014.v.filtered.vcf.gz>"$DV_root"testPop_1014.dv.filtered.bcftools_stats.txt

tabix -p vcf  "$DV_root"testPop_1014.dv.norm.filtered.vcf.gz
bcftools stats "$DV_root"testPop_1014.dv.norm.filtered.vcf.gz>"$DV_root"testPop_1014.dv.norm.bcftools_stats.txt

#---------------**** DRAGEN ****---------------
bcftools view -f .,PASS /dragennfs/area16/Population/testPop_1030.jointGenotype.hard-filtered.vcf.gz -S ^list_exclude.csv -Oz -o /dragennfs/area16/Population/testPop_1014.pass.vcf.gz --threads 230

bcftools +fill-tags /dragennfs/area16/Population/testPop_1014.pass.vcf.gz -Oz -o /dragennfs/area16/Population/testPop_1014.filltags.pass.vcf.gz -- -t all

tabix -p vcf  /dragennfs/area16/Population/testPop_1014.filltags.pass.vcf.gz
vt decompose -s /dragennfs/area16/Population/testPop_1014.filltags.pass.vcf.gz |vt normalize - -r /home/shared/references/Homo_sapiens_assembly38.fasta | vt uniq - -o /dragennfs/area16/Population/testPop_1014.norm.filltags.pass.vcf.gz

vep -i /dragennfs/area16/Population/testPop_1014.norm.filltags.pass.vcf.gz --cache --cache_version 100 --dir_cache /home/shared/.vep/ --offline --gene_phenotype --variant_class --af_1kg --hgvs --regulatory --phased --allele_number --hgvsg -fasta /home/shared/.vep/homo_sapiens/100_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --output_file /dragennfs/area16/Population/testPop_1014.vep_severe.norm.filltags.pass.vcf.gz --fork 230  --buffer_size 30000 --minimal --vcf_info_field "ANN" --transcript_version --check_existing --af --max_af --af_gnomad --pubmed --most_severe --compress_output bgzip

vep -i /dragennfs/area16/Population/testPop_1014.norm.filltags.pass.vcf.gz --cache --cache_version 100 --dir_cache /home/shared/.vep/ --sift b --symbol --offline --polyphen b --gene_phenotype --variant_class --af_1kg --hgvs --regulatory --protein --biotype --phased --allele_number --transcript_version --ccds --domain --uniprot --hgvsg -fasta /home/shared/.vep/homo_sapiens/100_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --output_file /dragennfs/area16/Population/testPop_1014.vep.norm.filltags.pass.vcf.gz --force_overwrite --vcf --verbose --fork 230 --buffer_size 30000 --minimal --vcf_info_field "ANN" --transcript_version --tsl --appris --canonical --mane --domains --check_existing --af --max_af --af_gnomad --pubmed --compress_output bgzip

java -jar "${Picard_root}"picard.jar MakeSitesOnlyVcf I=/dragennfs/area16/Population/testPop_1014.norm.filltags.pass.vcf.gz O=/dragennfs/area16/Population/testPop_1014.sitesOnly.norm.filltags.pass.vcf.gz

vep -i /dragennfs/area16/Population/testPop_1014.sitesOnly.norm.filltags.pass.vcf.gz --cache --cache_version 100 --dir_cache /home/shared/.vep/ --offline --gene_phenotype --variant_class --af_1kg --hgvs --regulatory --phased --allele_number --hgvsg -fasta /home/shared/.vep/homo_sapiens/100_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --output_file /dragennfs/area16/Population/testPop_1014.sitesOnly.vep_severe.norm.filltags.pass.vcf.gz --fork 48  --buffer_size 30000 --minimal --vcf_info_field "ANN" --transcript_version --check_existing --af --max_af --af_gnomad --pubmed --most_severe --compress_output bgzip

vep -i /dragennfs/area16/Population/testPop_1014.sitesOnly.norm.filltags.pass.vcf.gz --cache --cache_version 100 --dir_cache /home/shared/.vep/ --sift b --symbol --offline --polyphen b --gene_phenotype --variant_class --af_1kg --hgvs --regulatory --protein --biotype --phased --allele_number --transcript_version --ccds --domain --uniprot --hgvsg -fasta /home/shared/.vep/homo_sapiens/100_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --output_file /dragennfs/area16/Population/testPop_1014.sitesOnly.vep.norm.filltags.pass.vcf.gz --force_overwrite --vcf --verbose --fork 48 --buffer_size 30000 --minimal --vcf_info_field "ANN" --transcript_version --tsl --appris --canonical --mane --domains --check_existing --af --max_af --af_gnomad --pubmed --compress_output bgzip